import { APPROACH_DAVID, TPE_T1 } from "./geo.ts";
import type { LiveDriver, LiveSnapshot } from "./types";

export const BOOKING = "ZF-82041";

export const seedDrivers: LiveDriver[] = [
  {
    id: "D-118",
    name: "David Chen",
    plate: "TPE-4410",
    vehicle: "Toyota Alphard",
    klass: "MPV",
    rating: 4.92,
    accept: 0.96,
    onTime: 0.98,
    ridesWithSarah: 12,
    lastRide: "18 Sep",
    state: "available",
    loc: APPROACH_DAVID[0],
    heading: 38,
    km: 18,
    etaMin: 24,
    fleet: "A",
    onlineHours: 6.4,
    duty: "online",
  },
  {
    id: "D-221",
    name: "Jason Wu",
    plate: "TPE-2291",
    vehicle: "Toyota Alphard",
    klass: "MPV",
    rating: 4.87,
    accept: 0.94,
    onTime: 0.95,
    ridesWithSarah: 2,
    lastRide: "02 Aug",
    state: "available",
    loc: { lat: 25.0861, lng: 121.2412 },
    heading: 210,
    km: 1.2,
    etaMin: 4,
    fleet: "A",
    onlineHours: 5.1,
    duty: "online",
  },
  {
    id: "D-308",
    name: "Michael Lin",
    plate: "TPE-8802",
    vehicle: "HiAce",
    klass: "Van",
    rating: 4.81,
    accept: 0.91,
    onTime: 0.93,
    ridesWithSarah: 0,
    lastRide: "—",
    state: "available",
    loc: { lat: 25.0914, lng: 121.2528 },
    heading: 188,
    km: 3.4,
    etaMin: 9,
    fleet: "B",
    onlineHours: 4.2,
    duty: "online",
  },
  {
    id: "D-204",
    name: "Wei Chen",
    plate: "TPE-1188",
    vehicle: "Camry",
    klass: "Sedan",
    rating: 4.9,
    accept: 0.95,
    onTime: 0.96,
    ridesWithSarah: 1,
    lastRide: "11 Jul",
    state: "busy",
    loc: { lat: 25.0482, lng: 121.512 },
    heading: 92,
    km: 22,
    etaMin: 31,
    fleet: "A",
    onlineHours: 7.8,
    duty: "busy",
  },
  {
    id: "D-512",
    name: "Mina Park",
    plate: "KHH-6602",
    vehicle: "Camry",
    klass: "Sedan",
    rating: 4.88,
    accept: 0.93,
    onTime: 0.94,
    ridesWithSarah: 0,
    lastRide: "—",
    state: "available",
    loc: { lat: 25.0602, lng: 121.2188 },
    heading: 12,
    km: 2.8,
    etaMin: 7,
    fleet: "A",
    onlineHours: 3.6,
    duty: "online",
  },
];

export function initialSnapshot(): LiveSnapshot {
  return {
    scenario: "pickup",
    playing: false,
    sim: true,
    clock: "19:28",
    phase: "booked",
    bookingId: BOOKING,
    passenger: "Sarah Chen",
    flight: "BR156",
    flightStatus: "On time · NRT",
    delayMin: 0,
    terminal: "T2",
    pickup: "TPE T2 Arrivals · Door 8",
    dropoff: "Taipei 101 / Xinyi",
    assignedId: null,
    replacementId: null,
    otp: "4821",
    fare: 2280,
    etaMin: 0,
    distanceKm: 0,
    traffic: "clear",
    trafficNote: "National Freeway 1 flowing.",
    route: [TPE_T1],
    drivers: seedDrivers,
    events: [],
    incident: null,
    candidates: [],
    offerTo: null,
    customerNotice: null,
    preferred: null,
    counters: {
      active: 18,
      unassigned: 4,
      available: 64,
      busy: 31,
      arrivals: 11,
      delayed: 2,
      incidents: 0,
      sos: 0,
    },
  };
}
