import { APPROACH_DAVID, TPE_T1 } from "./geo.ts";
import type { LiveDriver, LiveSnapshot } from "./types";

export const BOOKING = "ZF-82041";

export const seedDrivers: LiveDriver[] = [
  {
    id: "D-118",
    name: "David Chen",
    plate: "TPE-4410",
    vehicle: "Toyota Alphard",
    klass: "MPV",
    rating: 4.92,
    accept: 0.96,
    onTime: 0.98,
    ridesWithSarah: 12,
    lastRide: "18 Sep",
    state: "available",
    loc: APPROACH_DAVID[0],
    heading: 38,
    km: 18,
    etaMin: 24,
    fleet: "A",
    onlineHours: 6.4,
    duty: "online",
  },
  {
    id: "D-221",
    name: "Jason Wu",
    plate: "TPE-2291",
    vehicle: "Toyota Alphard",
    klass: "MPV",
    rating: 4.87,
    accept: 0.94,
    onTime: 0.95,
    ridesWithSarah: 2,
    lastRide: "02 Aug",
    state: "available",
    loc: { lat: 25.0861, lng: 121.2412 },
    heading: 210,
    km: 1.2,
    etaMin: 4,
    fleet: "A",
    onlineHours: 5.1,
    duty: "online",
  },
  {
    id: "D-308",
    name: "Michael Lin",
    plate: "TPE-8802",
    vehicle: "HiAce",
    klass: "Van",
    rating: 4.81,
    accept: 0.91,
    onTime: 0.93,
    ridesWithSarah: 0,
    lastRide: "—",
    state: "available",
    loc: { lat: 25.0914, lng: 121.2528 },
    heading: 188,
    km: 3.4,
    etaMin: 9,
    fleet: "B",
    onlineHours: 4.2,
    duty: "online",
  },
  {
    id: "D-204",
    name: "Wei Chen",
    plate: "TPE-1188",
    vehicle: "Camry",
    klass: "Sedan",
    rating: 4.9,
    accept: 0.95,
    onTime: 0.96,
    ridesWithSarah: 1,
    lastRide: "11 Jul",
    state: "busy",
    loc: { lat: 25.0482, lng: 121.512 },
    heading: 92,
    km: 22,
    etaMin: 31,
    fleet: "A",
    onlineHours: 7.8,
    duty: "busy",
  },
  {
    id: "D-512",
    name: "Mina Park",
    plate: "KHH-6602",
    vehicle: "Camry",
    klass: "Sedan",
    rating: 4.88,
    accept: 0.93,
    onTime: 0.94,
    ridesWithSarah: 0,
    lastRide: "—",
    state: "available",
    loc: { lat: 25.0602, lng: 121.2188 },
    heading: 12,
    km: 2.8,
    etaMin: 7,
    fleet: "A",
    onlineHours: 3.6,
    duty: "online",
  },
];

export function initialSnapshot(): LiveSnapshot {
  return {
    scenario: "pickup",
    playing: false,
    sim: true,
    clock: "19:28",
    phase: "booked",
    bookingId: BOOKING,
    passenger: "Sarah Chen",
    flight: "BR156",
    flightStatus: "On time · NRT",
    delayMin: 0,
    terminal: "T2",
    pickup: "TPE T2 Arrivals · Door 8",
    dropoff: "Taipei 101 / Xinyi",
    assignedId: null,
    replacementId: null,
    otp: "4821",
    fare: 2280,
    etaMin: 0,
    distanceKm: 0,
    traffic: "clear",
    trafficNote: "National Freeway 1 flowing.",
    route: [TPE_T1],
    drivers: seedDrivers,
    events: [
      {
        id: "E-S1",
        at: Date.parse("2026-09-23T12:00:00+08:00"),
        clock: "12:00",
        type: "booking.created",
        severity: "info",
        audience: ["passenger", "ops", "system"],
        title: "ZF-82041 confirmed",
        body: "Sarah Chen · BR156 · TPE T2 Door 8 · NT$2280",
      },
      {
        id: "E-S2",
        at: Date.parse("2026-09-23T12:08:00+08:00"),
        clock: "12:08",
        type: "dispatch.offer.sent",
        severity: "action",
        audience: ["driver", "ops"],
        title: "Offer sent · D-118",
        body: "Company offer to David Chen · MPV Alphard",
      },
      {
        id: "E-S3",
        at: Date.parse("2026-09-23T12:09:00+08:00"),
        clock: "12:09",
        type: "notify.customer",
        severity: "info",
        audience: ["passenger"],
        title: "Driver assignment pending company confirmation",
        body: "You never book a driver privately.",
      },
      {
        id: "E-S4",
        at: Date.parse("2026-09-23T16:10:00+08:00"),
        clock: "16:10",
        type: "flight.status.changed",
        severity: "info",
        audience: ["ops", "driver", "passenger"],
        title: "BR156 on time · NRT",
        body: "T2 · monitoring until door assignment",
      },
    ],
    incident: null,
    candidates: [],
    offerTo: null,
    offerExpiresAt: null,
    offerRemainSec: null,
    offerStatus: null,
    rejectedOfferIds: [],
    offerKind: null,
    customerNotice: null,
    preferred: null,
    shareToken: null,
    rejects: {},
    counters: {
      active: 0,
      unassigned: 0,
      available: 0,
      busy: 0,
      arrivals: 0,
      delayed: 0,
      incidents: 0,
      sos: 0,
    },
  };
}
