export type Screen = {
  n?: number;
  group: string;
  name: string;
  href: string;
  note: string;
};

export const screens: Screen[] = [
  { n: 1, group: "Passenger", name: "Home", href: "/", note: "Mobility discovery, not a dashboard" },
  { n: 2, group: "Passenger", name: "Airport booking", href: "/book/airport", note: "Pickup journey, flight strip, meet instructions" },
  { group: "Passenger", name: "Airport drop-off", href: "/book/airport?mode=drop", note: "Leave-by timeline" },
  { n: 3, group: "Passenger", name: "Point-to-point", href: "/book/transfer", note: "Stops and route" },
  { group: "Passenger", name: "Hourly charter", href: "/book/charter", note: "Duration, overtime, distance policy" },
  { group: "Passenger", name: "Self-drive rental", href: "/book/rental", note: "Terms, deposit, requirements" },
  { group: "Passenger", name: "Instant taxi", href: "/book/taxi", note: "Nearby cars, ETA, category" },
  { n: 4, group: "Passenger", name: "Vehicle selection", href: "/book/ride", note: "Capacity matching and comparison" },
  { n: 5, group: "Passenger", name: "Checkout", href: "/book/confirm", note: "Fare, wallet, payment, policy" },
  { n: 6, group: "Passenger", name: "Confirmation", href: "/book/done", note: "Reference and next step" },
  { n: 7, group: "Passenger", name: "My trips", href: "/trips", note: "Upcoming, active, completed, cancelled" },
  { n: 8, group: "Passenger", name: "Booking detail", href: "/trips/ZD-1812", note: "Canonical booking, timeline, cancel" },
  { n: 9, group: "Passenger", name: "Live trip", href: "/live", note: "Map, OTP, SOS, share" },
  { n: 10, group: "Passenger", name: "Wallet", href: "/wallet", note: "Balance, credits, ledger" },
  { n: 11, group: "Passenger", name: "Referral", href: "/referral", note: "Code, channels, rewards" },
  { n: 12, group: "Passenger", name: "AI planner", href: "/planner", note: "Itinerary, map, budget. Does not purchase." },
  { n: 13, group: "Passenger", name: "Support", href: "/support", note: "Assistant, booking help, escalation" },
  { n: 14, group: "Passenger", name: "Profile", href: "/account", note: "Membership, preferences, saved people" },
  { n: 15, group: "Driver", name: "Driver home", href: "/driver", note: "Online state and current action" },
  { n: 16, group: "Driver", name: "Incoming offer", href: "/driver/offer", note: "Countdown, accept, reject" },
  { n: 17, group: "Driver", name: "Active pickup", href: "/driver/pickup", note: "Navigate to pickup" },
  { n: 18, group: "Driver", name: "OTP", href: "/driver/otp", note: "Verify passenger" },
  { n: 19, group: "Driver", name: "Active trip", href: "/driver/trip", note: "Navigate and complete" },
  { n: 20, group: "Driver", name: "Earnings", href: "/driver/earnings", note: "Today, week, month, adjustments" },
  { n: 21, group: "Driver", name: "Settlement", href: "/driver/settlement", note: "Statement and payment status" },
  { n: 22, group: "Driver", name: "Documents", href: "/driver/documents", note: "Compliance and re-upload" },
  { n: 23, group: "Operations", name: "Command center", href: "/ops", note: "Map, queue, inspector" },
  { n: 24, group: "Operations", name: "Booking queue", href: "/ops/queue", note: "Operational filters and search" },
  { n: 25, group: "Operations", name: "Booking inspector", href: "/ops/inspector", note: "Contextual dossier, no page reload inside command" },
  { n: 26, group: "Operations", name: "Dispatch board", href: "/ops/dispatch", note: "Explainable driver ranking" },
  { n: 27, group: "Operations", name: "Fleet map", href: "/ops/fleet-map", note: "Status markers and filters" },
  { n: 28, group: "Operations", name: "Flight board", href: "/ops/flights", note: "Delays and affected bookings" },
  { n: 29, group: "Operations", name: "Driver management", href: "/ops/drivers", note: "Directory and profile" },
  { n: 30, group: "Operations", name: "Fleet management", href: "/ops/fleet", note: "Company, franchise, partner" },
  { n: 31, group: "Operations", name: "Manual order entry", href: "/ops/manual", note: "Phone, corporate, support" },
  { n: 32, group: "Operations", name: "Safety incident", href: "/ops/safety", note: "Severity, timeline, escalation" },
  { n: 33, group: "Operations", name: "Support workspace", href: "/ops/support", note: "Conversation plus booking context" },
  { n: 34, group: "Admin", name: "Pricing", href: "/admin/pricing", note: "Factors, simulation, shadow, rollback" },
  { n: 35, group: "Admin", name: "Cancellation policy", href: "/admin/cancellation", note: "Bands and what-if" },
  { n: 36, group: "Admin", name: "Payments", href: "/admin/payments", note: "Authorization, capture, failure" },
  { n: 37, group: "Admin", name: "Refunds", href: "/admin/refunds", note: "Review, override, audit" },
  { n: 38, group: "Admin", name: "Settlements", href: "/admin/settlements", note: "Driver and partner statements" },
  { n: 39, group: "Admin", name: "Wallet ledger", href: "/admin/wallet", note: "Adjustments and expiry" },
  { n: 40, group: "Admin", name: "Referral management", href: "/admin/referrals", note: "Channel, conversion, fraud" },
  { n: 41, group: "Admin", name: "CRM", href: "/admin/crm", note: "Customer 360" },
  { n: 42, group: "Admin", name: "Analytics", href: "/admin/analytics", note: "Role-specific, not a KPI wall" },
  { n: 43, group: "Admin", name: "Promotions", href: "/admin/promotions", note: "Campaigns and limits" },
  { n: 44, group: "Admin", name: "Translation", href: "/admin/translations", note: "Traditional Chinese and English" },
  { n: 45, group: "Admin", name: "Notifications", href: "/admin/notifications", note: "Templates and delivery" },
  { n: 46, group: "Admin", name: "Integrations", href: "/admin/integrations", note: "Status without secrets" },
  { n: 47, group: "Admin", name: "Audit", href: "/admin/audit", note: "Actor, before, after" },
  { group: "Admin", name: "Vehicles", href: "/admin/vehicles", note: "Class, plate, maintenance" },
  { group: "Admin", name: "Accounts", href: "/admin/accounts", note: "Customers, drivers, staff, partners" },
  { group: "Admin", name: "Corporate", href: "/admin/corporate", note: "Policy, cost center, invoices" },
  { group: "Admin", name: "Parameters", href: "/admin/parameters", note: "Versioned operating rules" },
  { group: "Public", name: "Destinations", href: "/destinations", note: "City index" },
  { group: "Public", name: "City page", href: "/destinations/taipei", note: "SEO destination" },
  { group: "Public", name: "Route page", href: "/routes/tpe-taipei-101", note: "Corridor commerce page" },
  { group: "Public", name: "Service page", href: "/services/airport-transfer", note: "Service explanation and FAQ" },
  { group: "System", name: "Sign in", href: "/login", note: "Three role doors" },
  { group: "System", name: "Design studio", href: "/design", note: "Tokens, navigation, inventory" },
  { group: "System", name: "States", href: "/design/states", note: "Loading, empty, error, offline" },
];

export const navGroups = {
  passenger: [
    { href: "/", en: "Discover", zh: "探索" },
    { href: "/trips", en: "Trips", zh: "行程" },
    { href: "/planner", en: "Plan", zh: "規劃" },
    { href: "/wallet", en: "Wallet", zh: "錢包" },
    { href: "/support", en: "Support", zh: "支援" },
  ],
  passengerMobile: [
    { href: "/", en: "Home", zh: "首頁" },
    { href: "/trips", en: "Trips", zh: "行程" },
    { href: "/live", en: "Live", zh: "即時" },
    { href: "/planner", en: "Plan", zh: "規劃" },
    { href: "/account", en: "You", zh: "帳戶" },
  ],
  driver: [
    { href: "/driver", en: "Duty", zh: "出勤" },
    { href: "/driver/pickup", en: "Job", zh: "任務" },
    { href: "/driver/earnings", en: "Pay", zh: "收入" },
    { href: "/driver/documents", en: "Papers", zh: "證件" },
  ],
};
